/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-error-container": "#93000a",
              "surface-bright": "#faf9fd",
              "on-tertiary-fixed": "#181c1e",
              "primary-container": "#1b365d",
              "surface-variant": "#e3e2e6",
              "on-tertiary": "#ffffff",
              "on-secondary-container": "#586377",
              "surface-container-high": "#e9e7eb",
              "background": "#faf9fd",
              "on-tertiary-container": "#9ca0a2",
              "primary-fixed-dim": "#aec7f7",
              "on-background": "#1a1b1e",
              "surface-container-lowest": "#ffffff",
              "on-primary-fixed-variant": "#2e476f",
              "surface-container-low": "#f4f3f7",
              "surface-tint": "#465f88",
              "secondary-container": "#d5e0f7",
              "tertiary-fixed-dim": "#c3c7c9",
              "error": "#ba1a1a",
              "on-primary-container": "#87a0cd",
              "outline-variant": "#c4c6cf",
              "secondary-fixed-dim": "#bcc7dd",
              "surface-container-highest": "#e3e2e6",
              "on-secondary-fixed-variant": "#3c475a",
              "on-secondary": "#ffffff",
              "on-secondary-fixed": "#111c2c",
              "surface-container": "#efedf1",
              "inverse-primary": "#aec7f7",
              "tertiary-container": "#333739",
              "on-tertiary-fixed-variant": "#434749",
              "outline": "#74777f",
              "secondary-fixed": "#d8e3fa",
              "on-primary": "#ffffff",
              "tertiary-fixed": "#e0e3e5",
              "tertiary": "#1d2223",
              "secondary": "#545f72",
              "inverse-surface": "#2f3033",
              "primary": "#002046",
              "surface-dim": "#dad9dd",
              "error-container": "#ffdad6",
              "on-primary-fixed": "#001b3d",
              "on-surface-variant": "#44474e",
              "on-error": "#ffffff",
              "primary-fixed": "#d6e3ff",
              "surface": "#faf9fd",
              "inverse-on-surface": "#f1f0f4",
              "on-surface": "#1a1b1e"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "unit": "4px",
              "stack-md": "16px",
              "stack-lg": "32px",
              "container-padding": "24px",
              "stack-sm": "8px",
              "gutter": "16px"
      },
      "fontFamily": {
              "headline-md-mobile": ["Inter"],
              "body-lg": ["Inter"],
              "mono-label": ["Space Mono"],
              "label-caps": ["Inter"],
              "title-sm": ["Inter"],
              "display-lg": ["Inter"],
              "headline-md": ["Inter"],
              "body-sm": ["Inter"]
      },
      "fontSize": {
              "headline-md-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
              "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "mono-label": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
              "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
              "title-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
              "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
              "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
